default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Cogumelos_development

test:
  <<: *default
  database: Cogumelos_test

production:
  <<: *default
  database: Cogumelos_production
  username: Cogumelos
  password: <%= ENV["COGUMELOS_DATABASE_PASSWORD"] %>
